//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnviarMAILS.ShippingAll {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:servicename", ConfigurationName="ShippingAll.servicenamePortType")]
    public interface servicenamePortType {
        
        // CODEGEN: Parameter 'Pass' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://uvm056.dei.isep.ipp.pt/~uvm056/ShippingAll.php#custo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Pass")]
        EnviarMAILS.ShippingAll.custoResponse custo(EnviarMAILS.ShippingAll.custoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://uvm056.dei.isep.ipp.pt/~uvm056/ShippingAll.php#custo", ReplyAction="*")]
        System.Threading.Tasks.Task<EnviarMAILS.ShippingAll.custoResponse> custoAsync(EnviarMAILS.ShippingAll.custoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="custo", WrapperNamespace="urn:servicename", IsWrapped=true)]
    public partial class custoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:servicename", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int x;
        
        public custoRequest() {
        }
        
        public custoRequest(int x) {
            this.x = x;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="custoResponse", WrapperNamespace="urn:servicename", IsWrapped=true)]
    public partial class custoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:servicename", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float Pass;
        
        public custoResponse() {
        }
        
        public custoResponse(float Pass) {
            this.Pass = Pass;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicenamePortTypeChannel : EnviarMAILS.ShippingAll.servicenamePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicenamePortTypeClient : System.ServiceModel.ClientBase<EnviarMAILS.ShippingAll.servicenamePortType>, EnviarMAILS.ShippingAll.servicenamePortType {
        
        public servicenamePortTypeClient() {
        }
        
        public servicenamePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicenamePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicenamePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicenamePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnviarMAILS.ShippingAll.custoResponse EnviarMAILS.ShippingAll.servicenamePortType.custo(EnviarMAILS.ShippingAll.custoRequest request) {
            return base.Channel.custo(request);
        }
        
        public float custo(int x) {
            EnviarMAILS.ShippingAll.custoRequest inValue = new EnviarMAILS.ShippingAll.custoRequest();
            inValue.x = x;
            EnviarMAILS.ShippingAll.custoResponse retVal = ((EnviarMAILS.ShippingAll.servicenamePortType)(this)).custo(inValue);
            return retVal.Pass;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EnviarMAILS.ShippingAll.custoResponse> EnviarMAILS.ShippingAll.servicenamePortType.custoAsync(EnviarMAILS.ShippingAll.custoRequest request) {
            return base.Channel.custoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EnviarMAILS.ShippingAll.custoResponse> custoAsync(int x) {
            EnviarMAILS.ShippingAll.custoRequest inValue = new EnviarMAILS.ShippingAll.custoRequest();
            inValue.x = x;
            return ((EnviarMAILS.ShippingAll.servicenamePortType)(this)).custoAsync(inValue);
        }
    }
}
