//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnviarMAILS.LogisticaSA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogisticaSA.IServiceLogisticaSA")]
    public interface IServiceLogisticaSA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogisticaSA/DoWork", ReplyAction="http://tempuri.org/IServiceLogisticaSA/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogisticaSA/DoWork", ReplyAction="http://tempuri.org/IServiceLogisticaSA/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogisticaSA/custo", ReplyAction="http://tempuri.org/IServiceLogisticaSA/custoResponse")]
        float custo(int quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLogisticaSA/custo", ReplyAction="http://tempuri.org/IServiceLogisticaSA/custoResponse")]
        System.Threading.Tasks.Task<float> custoAsync(int quantidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLogisticaSAChannel : EnviarMAILS.LogisticaSA.IServiceLogisticaSA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLogisticaSAClient : System.ServiceModel.ClientBase<EnviarMAILS.LogisticaSA.IServiceLogisticaSA>, EnviarMAILS.LogisticaSA.IServiceLogisticaSA {
        
        public ServiceLogisticaSAClient() {
        }
        
        public ServiceLogisticaSAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLogisticaSAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLogisticaSAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLogisticaSAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public float custo(int quantidade) {
            return base.Channel.custo(quantidade);
        }
        
        public System.Threading.Tasks.Task<float> custoAsync(int quantidade) {
            return base.Channel.custoAsync(quantidade);
        }
    }
}
